name: Build & Publish

on:
  push:
    branches:
      - "**"             # all branches
      - "!dependabot/**"      # exclude dependbot branches
  workflow_dispatch:      # Manually run the workflow

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './app'
      steps:
        - name: 'Checkout Action'
          uses: actions/checkout@main

        - name: