name: Build & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:      # Manually run the workflow
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './app'
      steps:
        - name: Checkout Action
          uses: actions/checkout@main

        - name: